version: '3'

services:
  web:
    container_name: tsy-cms-ui
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_S3_ACCESS_KEY=$VITE_S3_ACCESS_KEY
        - VITE_S3_SECRET_KEY=$VITE_S3_SECRET_KEY
        - VITE_S3_BUCKET_NAME=$VITE_S3_BUCKET_NAME
        - VITE_AWS_REGION=$VITE_AWS_REGION
        - VITE_TSY_API=$VITE_VITE_TSY_API
    ports:
      - 80:80
    restart: always
    env_file:
      - .env
  